Feature/VirtualVendingMachine
liskis/reviewTest pull request #4
Opened 2023-11-22 02:11 UTC by liskis

VirtualVendingMachineを改造しました

2023-11-22 03:33 UTC, LunaChevalier reviewed
プルリクエストの概要部分に

> VirtualVendingMachineを改造しました

と記載されていますが、どういった改造を施したのか、箇条書きで大丈夫なので、記載お願いします!

2023-11-22 03:34 UTC, LunaChevalier commented
もう一つありました
プルリクエストのタイトルも、簡単でOKなので、どういった内容のプルリクエストなのか記載するとわかりやすいです

2023-11-22 05:48 UTC, liskis commented
どうやって書き換えたら良いですか？

2023-11-22 09:56 UTC, LunaChevalier requested changes
改良自体はいい感じに実装できていると思います!
不要なファイルやTypoなどがありますので、こちらの修正をしてもらえればと思います

2023-11-22 09:56 UTC, LunaChevalier commented on .DS_Store
![must](https://img.shields.io/badge/review-must-red.svg) 
`.gitignore`で追跡対象外にしていますが、`.gitignore`を追加したコミットで一緒にコミットされているので、除外されていないです
`git rm --cached .DS_Store`で追跡対象から削除する様にしてください
以下は参考記事になります
[.gitignoreを後から設定し、git管理から除外する方法 #Git - Qiita](https://qiita.com/yutosa3/items/25ab031c8061e8c9a4c4)

2023-11-22 09:56 UTC, LunaChevalier commented on MyPlayground.playground/Contents.swift
> +    var chengeAmount: Int = 0
![must](https://img.shields.io/badge/review-must-red.svg) 
```suggestion
    var changeAmount: Int = 0
```
お釣りを意味する変数だと思いますが、`change`が正しい綴りになります

2023-11-22 09:56 UTC, LunaChevalier commented on MyPlayground.playground/Contents.swift
> +
![suggest](https://img.shields.io/badge/review-suggest-success.svg) 
改行が2つ入っていると思います
基本的には1つだけでOKです!

2023-11-22 09:56 UTC, LunaChevalier commented on MyPlayground.playground/playground.xcworkspace/xcuserdata/watanabekensuke.xcuserdatad/UserInterfaceState.xcuserstate
![must](https://img.shields.io/badge/review-must-red.svg) 
こちらのファイルですが、Xcodeの以下の状態を保存したファイルになります

- どのファイルを開いている状態か
- カーソルをどこに当てているか

なので、コミットする必要が無いため`.gitignore`にこちらのファイルを追加して、追跡対象外にしてください

2023-11-22 09:56 UTC, LunaChevalier commented on MyPlayground.playground/Contents.swift
> +    var chengeAmount: Int = 0
![should](https://img.shields.io/badge/review-should-orange.svg) 
`buyDrink`でしか使われてないので、このメソッドのローカル変数として扱ったほうがバグの発生が少なくなります

2023-11-23 00:45 UTC, liskis commented
修正しました

2023-11-23 01:36 UTC, LunaChevalier commented on MyPlayground.playground/playground.xcworkspace/xcuserdata/watanabekensuke.xcuserdatad/UserInterfaceState.xcuserstate
追跡対象外から外れてないです
`.DS_Store`と同様に、一度追跡対象にしたファイルは`git rm`で追跡対象外にしないといけないので、そちらを実行してください

2023-11-23 01:37 UTC, LunaChevalier requested changes
一部、前回のコメントが対応できてないので、修正お願いします!

2023-11-23 01:37 UTC, LunaChevalier commented on MyPlayground.playground/Contents.swift
> +
2行改行が入っているので、1行にしてください!

2023-11-24 00:02 UTC, LunaChevalier approved these changes

2023-11-24 00:50 UTC, merged